# Generated by Django 4.2.1 on 2023-06-01 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_demo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='level',
            field=models.CharField(default='trainee', max_length=30),
        ),
    ]
