# Generated by Django 4.2.1 on 2023-06-01 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_demo', '0003_employee_work_full_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='work_full_time',
            field=models.BooleanField(default=True),
        ),
    ]
