# Generated by Django 4.2.1 on 2023-06-01 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_demo', '0006_departments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='departments',
            name='department_name',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
