# Generated by Django 4.2.1 on 2023-06-01 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_demo', '0010_projects'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='projects',
            field=models.ManyToManyField(to='app_demo.projects'),
        ),
    ]
