# Generated by Django 4.2.1 on 2023-06-02 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_demo', '0012_departments_created_on_departments_updated_on_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='departments',
            options={'verbose_name_plural': 'Departments'},
        ),
        migrations.AddField(
            model_name='departments',
            name='slug',
            field=models.SlugField(null=True, unique=True),
        ),
    ]
