# Generated by Django 4.2.1 on 2023-06-10 08:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0004_alter_photo_photo'),
        ('common', '0002_create_comment_and_like'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Comment',
            new_name='PhotoComment',
        ),
        migrations.RenameModel(
            old_name='Like',
            new_name='PhotoLike',
        ),
    ]
